### ISSUE TITLE
Bug:Multiple dex file 

### ISSUE THREAD

**Issue by AlbertSnow** [tgioihan/androidcore#1]
Hello 
  I check out full project androidcore. But i meet a problem,the stack is "Unable to execute dex: Multiple dex files define Lcom/facebook/AccessToken$SerializationProxyV1;"
  And compile the project is ok, but run the project is crush.
  Can you run the project normally? Did you meet the problem.Please tell me if you solve this problem.Thanks

**Comment by tgioihan** [comment]
pls remove facebooksdk.jar in libs folder of core's module

**Comment by AlbertSnow** [comment]
Hi tgioihan, Thank you very much for answer to me.But I still get problem.When I delete the facebooksdk.jar in libs folder, I even can't pass compile,and The message show "Program package 'com.facebook is not exist".
